apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ccm-plugin
  annotations:
    harness.io/perspective-url:
spec:
  type: service
  lifecycle: experimental
  owner: 
  system: 
  dependsOn:
